<a href="https://colab.research.google.com/github/dhruvdev30/Python-Basics/blob/main/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Function() - Inbuilt /User Defined
2. Variables - It holds values (ANy datatype)

In [ ]:
print("Hello World")

In [ ]:
"Hello World"

In [ ]:
subject =  input("What are you learning? ")
print("I am learning",subject)

In [ ]:
# Assignment : Take 2 variables as input and assign the numbers
# Print the sum of 2 numbers

In [ ]:
a = 1
type(a)

In [ ]:
a = 1.1
type(a)

In [ ]:
a = 'A'
type(a) # No char datatype in Python

In [ ]:
a = "Python"
type(a)

In [ ]:
a = int(input("Enter 1st number"))
b = int(input("Enter 2nd number"))
add = a+b
print(add)


In [ ]:
# The sum of 12 and 34 is 46
# Method 1: Using + operator
print("The sum of "+str(a)+" and " +str(b)+ " is " +str(add))
# Method 2: Using , operator
print("The sum of",a,"and",b,"is",add)
# Method 3: String Formatting
print(f"The sum of {a} and {b} is {add}")

In [ ]:
'Py'+'thon' # COncatenation

In [ ]:
int('12')+int('34')

# In built FUnctions
1. print()
2. input()
3. int()
4. type()
5. str()
6. float()

https://docs.python.org/3/library/functions.html

In [ ]:
# Conditions and loops

In [ ]:
# if , elif, else

In [ ]:
a = 3
3%2

In [ ]:
a = int(input("Enter the number"))
if a%2==0:
  print(f'{a} is even number')
else:
  print(f'{a} is odd number')

In [ ]:
# Elif = ELse if

In [ ]:
# Loop : repeatition

In [ ]:
# 1. Entry controlled loop - for and while
# 2. Exit Controlled loop - do while

In [ ]:
#print("Python")

i = 0
while i<=4:
  print(i,end=' ')
  i+=1

0 1 2 3 4 

In [ ]:
# Print a multiplication table
# 5 x 1 = 5
# 5 x 2 = 10
.
.
.
# 5 x 10 = 50

In [ ]:
n = int(input('Enter the number:'))
i = 1
while i<=10:
  print(f'{n} x {i} = {n*i}')
  i+=1

In [ ]:
# Write a forever loop
# Take input in the form of message
# If message = Hello | Hi | Hey then print "Hello User"
# If message = How are you then print "I am fine"
# if message = Bye then print "Bye User",it should come out of the loop
# if anything else, print (I dont understand)
# If you give more than 3 times anything else, then stop the program

# What you need to explore?
# 1. How to get a forver loop?
# 2. How to put Hello | Hi | Hey in one condition
# 3. How to exit from a loop?

# YOU DONT HAVE TO SUBMIT YOUR ASSIGNMENT> IT IS JUST FOR YOUR REFERENCE

In [ ]:
# Advanced Datatypes and Libraries
# List,String, Dictionary
# Numpy : Arrays [Tensors] - Numerical Computing
# Matplotlib and Seaborn - Data Visualization
# Pandas : Exploratory Data analysis
# Streamlit : Web App 

In [ ]:
# for loop
# Initialization,Condition, Increment/Decrement

In [ ]:
# Range (Start Value, End Value,Step)
# Method 1: range(num1) num1 - Last + 1 Value , Starting Value =0,Step=1
print(list(range(10)))
# Method 2: range(num1,num2) || num1 = Starting value, num2 = End Value, Step =1
print(list(range(5,10)))
# Method 3: range(num1,num2,num3) || num1 = Start value, num2 = ENd Value , num3 = Step
print(list(range(3,20,3)))

print(list(range(50,4,-5)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[5, 6, 7, 8, 9]
[3, 6, 9, 12, 15, 18]
[50, 45, 40, 35, 30, 25, 20, 15, 10, 5]


In [ ]:
range?

In [ ]:
#50 to 5
# 50,45,40,35,30,25,20,15,10,5

In [ ]:
for i in range(5,10):
  print(i)

5
6
7
8
9


In [ ]:
# List : Advanced Datatype in Python ( Sequence )
# List is Mutable : It can be changed (Update can be done)
a_list = [1,'Python',1.1,True]
type(a_list)

list

In [ ]:
a_list

[1, 'Python', 1.1, True]

In [ ]:
for i in a_list:
  print(f'Component: {i}')

Component: 1
Component: Python
Component: 1.1
Component: True


In [ ]:
a_list[-1]

True

In [ ]:
a_list.append('Java')

In [ ]:
a_list

[1, 'Python', 1.1, True, 'Java']

In [ ]:
# List Functions: Append,Insert, pop, remove

In [ ]:
# Interview Questions
# Output of this code
list_a = [99,98,97,96]
list_b = list_a
list_b[2] = 0
print(list_a)

In [ ]:
# Libraries 
# Functions and Variables

# Libraries are considered as object.
# Object is an instance of a class

# Method(): Functions called from objects
# Attributes : Variables called from objects

In [ ]:
print("I am learning Python")

I am learning Python


In [ ]:
import numpy as np
a = np.array([[1,5,3],
          [3,4,5]],dtype='object')
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[1 5 3]
 [3 4 5]]
2
(2, 3)
6


In [ ]:
np.random.seed(123)# Controlling the randomness of the value
a = np.random.randint(1,100,10)
a = np.sort(a)
a
# Random generator : Seed value

array([18, 48, 58, 67, 84, 87, 93, 97, 98, 99])

In [ ]:
b = np.array([1,55,77,22,54,100])
b

array([  1,  55,  77,  22,  54, 100])

In [ ]:
# [0,0.5,0.7,0.2,0.53,1]

In [ ]:
# The Minimum gets replaced with 0
# Max Value gets replaced with 1
# All the other s will be in between 0 and 1

In [ ]:
b[-1]

100

In [ ]:
# Pandas : Panel Datas : Exploring the Data  [Data Analytics]
# This is the first step in ML/DS/AI Project

# Preprocessing
# Cleaning
# Normalization
# Handle Missing Data
# Removing Unwanted Data
# Try to answer some questions - Data Mining

# 2 imp objects: Dataframe and Series
# DataFrame : 2 Dimension [Matrix] : Rows and Columns
# Series : 1 Dimension[Vector]: Column

In [ ]:
# List/Array/Dictionary then use pd.DataFrame()
# Excel Sheets : pd.read_excel()
# csv Files ( Comma separated values) - pd.read_csv()
# json files(Javascript object Notation) -pd.read_json()
# HTML Files - pd.read_html()[-1]

In [ ]:
# Dictionary consists of Key and Value

d = {'Language':['Python','C++','C'],
     'Person':['Mr X','Mr Y',np.nan]}
d

{'Language': ['Python', 'C++', 'C'], 'Person': ['Mr X', 'Mr Y', nan]}

In [ ]:
type(d)

dict

In [ ]:
import pandas as pd
df = pd.DataFrame(d)
df

Language Person
0   Python   Mr X
1      C++   Mr Y
2        C    NaN

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
# Assignment : Create a DataFrame for a csv file from Kaggle Website

# SIgn in using Google
# Link for Dataset : https://www.kaggle.com/rtatman/chocolate-bar-ratings

# https://www.youtube.com/watch?v=gwDOUuBH7ws&t=639s&ab_channel=DiazonicLabs